export type WarmCompanySeed = {
  name: string;
  slug: string;
  domain: string | null;
  allowedDomains: string[];
  headquarters: string | null;
  employeeCount: string | null;
  brandColor: string | null;
  verified: boolean;
  description: string | null;
};

const buildSlug = (value: string) =>
  value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'company';

const toWarmCompany = (
  name: string,
  overrides: Partial<WarmCompanySeed> = {}
): WarmCompanySeed => {
  const domain = overrides.domain ?? null;
  return {
    name,
    slug: overrides.slug || buildSlug(name),
    domain,
    allowedDomains: overrides.allowedDomains || (domain ? [domain] : []),
    headquarters: overrides.headquarters ?? null,
    employeeCount: overrides.employeeCount ?? null,
    brandColor: overrides.brandColor ?? null,
    verified: false,
    description:
      overrides.description ??
      'Warm company catalog entry used for discovery, verification demand capture, and future vendor targeting.',
  };
};

const companyOverrides: Record<string, Partial<WarmCompanySeed>> = {
  'BC Hydro': { slug: 'bc-hydro' },
  'Lululemon Athletica': { slug: 'lululemon' },
  'University of British Columbia (UBC)': { slug: 'university-of-british-columbia' },
  'Simon Fraser University (SFU)': { slug: 'simon-fraser-university' },
  'University of Victoria (UVic)': { slug: 'university-of-victoria' },
  'British Columbia Institute of Technology (BCIT)': { slug: 'british-columbia-institute-of-technology' },
  'University of Northern British Columbia (UNBC)': { slug: 'university-of-northern-british-columbia' },
  'Thompson Rivers University (TRU)': { slug: 'thompson-rivers-university' },
  'Vancouver Island University (VIU)': { slug: 'vancouver-island-university' },
  'Kwantlen Polytechnic University (KPU)': { slug: 'kwantlen-polytechnic-university' },
};

const topEmployerNames = [
  'Royal Bank of Canada',
  'Toronto-Dominion Bank',
  'Shopify',
  'Agnico Eagle Mines',
  'Enbridge',
  'Canadian Natural Resources',
  'Brookfield',
  'Bank of Montreal',
  'Barrick Mining',
  'Canadian Imperial Bank of Commerce',
  'Bank of Nova Scotia',
  'Wheaton Precious Metals',
  'Suncor Energy',
  'Alimentation Couche-Tard',
  'Canadian Pacific Kansas City',
  'Franco-Nevada',
  'TC Energy',
  'Canadian National Railway',
  'China Gold International Resources',
  'Imperial Oil',
  'Manulife Financial',
  'Thomson Reuters',
  'Loblaw Companies',
  'Kinross Gold',
  'National Bank of Canada',
  'Constellation Software',
  'Nutrien',
  'Cenovus Energy',
  'Fairfax Financial Holdings',
  'Celestica',
  'Great-West Lifeco',
  'Sun Life Financial',
  'Cameco',
  'Dollarama',
  'Pan American Silver',
  'Intact Financial',
  'Power Corporation of Canada',
  'First Quantum Minerals',
  'Lundin Mining',
  'Fortis',
  'International Petroleum',
  'Alamos Gold',
  'George Weston',
  'Lundin Gold',
  'Pembina Pipeline',
  'Hydro One',
  'Bombardier',
  'BCE',
  'WSP Global',
  'Magna International',
  'Telus',
  'Lululemon Athletica',
  'Teck Resources',
  'Rogers Communications',
  'Tourmaline Oil',
  'Emera',
  'GFL Environmental',
  'IAMGOLD',
  'CGI',
  'Ivanhoe Mines',
  'Metro',
  'First Majestic Silver',
  'Gildan Activewear',
  'Whitecap Resources',
  'TFI International',
  'Saputo',
  'G Mining Ventures',
  'Element Fleet Management',
  'Hudbay Minerals',
  'Equinox Gold',
  'Toromont Industries',
  'DPM Metals',
  'IGM Financial',
  'ARC Resources',
  'AltaGas',
  'CCL Industries',
  'AtkinsRealis',
  'OR Royalties',
  'iA Financial Corporation',
  'Triple Flag Precious Metals',
  'OceanaGold',
  'TMX Group',
  'Stantec',
  'South Bow',
  'Eldorado Gold',
  'Canadian Utilities',
  'Aritzia',
  'New Gold',
  'Quebecor',
  'Topicus.com',
  'FirstService',
  'B2Gold',
  'Keyera',
  'Molson Coors Canada',
  'CAE',
  'Capstone Copper',
  'Orla Mining',
  'Descartes Systems Group',
  'Empire Company',
  'Finning International',
  'Ledcor Group',
  'PCL Construction',
  'EllisDon',
  'Chandos Construction',
  'Kinetic Construction',
  'Axiom Builders',
  'ITC Construction Group',
  'Ventana Construction',
  'Scott Construction Group',
  'Maple Reinders',
  'Graham Construction',
  'Turner Construction Canada',
  'Centra Windows',
  'Canadian Choice Windows & Doors',
  'Lux Windows and Glass',
  'Durabuilt Windows & Doors',
  'CertaPro Painters Canada',
  'Handyman Connection',
  'Mr. Rooter Plumbing Canada',
  'Mr. Electric Canada',
  'The Grounds Guys Canada',
  'Paul Davis Restoration Canada',
  'Sunrise Farms',
  'Sofina Foods',
  'Maple Lodge Farms',
  'Saputo',
  'Parmalat Canada',
  'Darigold Canada',
  'Lactalis Canada',
  'Olymel',
  'Maple Leaf Foods',
  'Cargill Canada',
  'Richardson International',
  'Griffith Foods',
  'TreeHouse Foods Canada',
  'Dare Foods',
  "Nature's Path Foods",
  'London Drugs',
  'Save-On-Foods',
  'Choices Markets',
  "Nature's Fare Markets",
  'Urban Barn',
  'Sleep Country Canada',
  'Structube',
  'Pet Valu',
  'Dollar Tree Canada',
  'Bulk Barn',
  'Day & Ross',
  'Challenger Motor Freight',
  'Canada Cartage',
  'VersaCold Logistics Services',
  'Mullen Group',
  'Bison Transport',
  'Manitoulin Transport',
  'Trimac Transportation',
  'Fastfrate Group',
  'Purolator',
  'Clio',
  'Hootsuite',
  'Thinkific',
  'Dapper Labs',
  'Jane App',
  'GeoComply',
  'Trulioo',
  'Kabam',
  'Bench Accounting',
  'FreshBooks',
  'Wolseley Canada',
  'Emco Corporation',
  'Bartle & Gibson',
  'Noble Corporation',
  'Westburne (Rexel Canada)',
  'EECOL Electric',
  'Gescan (Sonepar Canada)',
  'Guillevin International',
  'Graybar Canada',
  'Nedco (Rexel Canada)',
  'Andrew Sheret',
];

const publicSectorNames = [
  'Ministry of Agriculture and Food (BC)',
  'Ministry of Attorney General (BC)',
  'Ministry of Children and Family Development (BC)',
  "Ministry of Citizens' Services (BC)",
  'Ministry of Education and Child Care (BC)',
  'Ministry of Emergency Management and Climate Readiness (BC)',
  'Ministry of Energy and Climate Solutions (BC)',
  'Ministry of Environment and Parks (BC)',
  'Ministry of Finance (BC)',
  'Ministry of Forests (BC)',
  'Ministry of Health (BC)',
  'Ministry of Housing and Municipal Affairs (BC)',
  'Ministry of Indigenous Relations and Reconciliation (BC)',
  'Ministry of Infrastructure (BC)',
  'Ministry of Jobs and Economic Growth (BC)',
  'Ministry of Labour (BC)',
  'Ministry of Mining and Critical Minerals (BC)',
  'Ministry of Post-Secondary Education and Future Skills (BC)',
  'Ministry of Public Safety and Solicitor General (BC)',
  'Ministry of Social Development and Poverty Reduction (BC)',
  'Ministry of Tourism, Arts, Culture and Sport (BC)',
  'Ministry of Transportation and Transit (BC)',
  'Ministry of Water, Land and Resource Stewardship (BC)',
  'BC Hydro',
  'Insurance Corporation of British Columbia (ICBC)',
  'BC Transit',
  'British Columbia Lottery Corporation',
  'BC Housing',
  'BC Assessment',
  'BC Financial Services Authority',
  'BC Energy Regulator',
  'Infrastructure BC',
  'Innovate BC',
  'InBC Investment Corp',
  'Destination BC',
  'Knowledge Network',
  'Legal Aid BC',
  'Royal BC Museum',
  'SkilledTradesBC',
  'Community Living BC',
  'Columbia Basin Trust',
  'Forestry Innovation Investment',
  'BC Pavilion Corporation',
  'Fraser Health',
  'Interior Health',
  'Island Health',
  'Northern Health',
  'Vancouver Coastal Health',
  'Provincial Health Services Authority',
  'First Nations Health Authority',
  'RCMP E Division (BC)',
  'Surrey Police Service',
  'Vancouver Police Department',
  'Victoria Police Department',
  'Delta Police Department',
  'Abbotsford Police Department',
  'New Westminster Police Service',
  'Saanich Police Department',
  'West Vancouver Police Department',
  'Metro Vancouver Transit Police',
  'University of British Columbia (UBC)',
  'Simon Fraser University (SFU)',
  'University of Victoria (UVic)',
  'British Columbia Institute of Technology (BCIT)',
  'University of Northern British Columbia (UNBC)',
  'Thompson Rivers University (TRU)',
  'Vancouver Island University (VIU)',
  'Kwantlen Polytechnic University (KPU)',
  'Emily Carr University of Art + Design',
  'Royal Roads University',
  'Douglas College',
  'Langara College',
  'CBC British Columbia',
  'CTV News Vancouver',
  'Global BC (Corus Entertainment)',
  'CityNews Vancouver',
  'Vancouver Sun (Postmedia)',
  'The Province (Postmedia)',
  'Glacier Media',
  'Black Press Media',
  'Daily Hive',
  'Narcity Canada',
  'Business in Vancouver (BIV)',
  'Western Standard',
  'The Tyee',
  'Canada Wide Media',
  'Vancouver Magazine',
  'Georgia Straight',
  'Castanet Media',
  'KelownaNow',
  'CHEK News',
  'OMNI Television BC',
  'National Defence',
  'Canadian Armed Forces',
  'Canadian Army',
  'Royal Canadian Navy',
  'Royal Canadian Air Force',
  'Canadian Special Operations Forces Command',
  'Royal Canadian Mounted Police',
  'Canada Border Services Agency',
  'Canadian Security Intelligence Service',
  'Communications Security Establishment',
  'Public Safety Canada',
  'Canada Revenue Agency',
  'Employment and Social Development Canada',
  'Immigration, Refugees and Citizenship Canada',
  'Indigenous Services Canada',
  'Crown-Indigenous Relations and Northern Affairs Canada',
  'Health Canada',
  'Public Health Agency of Canada',
  'Public Services and Procurement Canada',
  'Innovation, Science and Economic Development Canada',
  'Natural Resources Canada',
  'Environment and Climate Change Canada',
  'Fisheries and Oceans Canada',
  'Canadian Food Inspection Agency',
  'National Research Council Canada',
  'Canada Mortgage and Housing Corporation',
  'Business Development Bank of Canada',
  'Export Development Canada',
  'Farm Credit Canada',
  'Canada Post',
];

export const WARM_COMPANY_CATALOG: WarmCompanySeed[] = Array.from(
  new Set([...topEmployerNames, ...publicSectorNames])
).map((name) => toWarmCompany(name, companyOverrides[name] || {}));
